### ISSUE TITLE
Segfault when removing a bookmark set as Bookmark Source

### ISSUE THREAD

**Issue by paper42** [skyjake/lagrange#154]
```
Core was generated by `lagrange'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  constData_Block (d=d@entry=0x18) at ../lib/the_Foundation/src/block.c:218
218	../lib/the_Foundation/src/block.c: No such file or directory.
[Current thread is 1 (Thread 0x7f09d99d6b80 (LWP 4442))]
#0  constData_Block (d=d@entry=0x18) at ../lib/the_Foundation/src/block.c:218
#1  0x000055fddc20fa95 in cstr_String (d=d@entry=0x18) at ../lib/the_Foundation/src/string.c:380
#2  0x000055fddc1b9ef0 in cmpTitle_Bookmark_ (a=<optimized out>, b=<optimized out>) at ../src/ui/sidebarwidget.c:127
#3  0x00007f09dac81735 in msort_with_tmp (p=p@entry=0x7ffe1a79f520, b=b@entry=0x55fddf6875b8, n=n@entry=2) at msort.c:83
#4  0x00007f09dac816a5 in msort_with_tmp (n=2, b=0x55fddf6875b8, p=0x7ffe1a79f520) at msort.c:45
#5  msort_with_tmp (p=p@entry=0x7ffe1a79f520, b=b@entry=0x55fddf6875b8, n=n@entry=4) at msort.c:53
#6  0x00007f09dac816a5 in msort_with_tmp (n=4, b=0x55fddf6875b8, p=0x7ffe1a79f520) at msort.c:45
#7  msort_with_tmp (p=p@entry=0x7ffe1a79f520, b=b@entry=0x55fddf6875b8, n=n@entry=9) at msort.c:53
#8  0x00007f09dac816a5 in msort_with_tmp (n=9, b=0x55fddf6875b8, p=0x7ffe1a79f520) at msort.c:45
#9  msort_with_tmp (p=p@entry=0x7ffe1a79f520, b=b@entry=0x55fddf6875b8, n=n@entry=18) at msort.c:53
#10 0x00007f09dac816a5 in msort_with_tmp (n=18, b=0x55fddf6875b8, p=0x7ffe1a79f520) at msort.c:45
#11 msort_with_tmp (p=p@entry=0x7ffe1a79f520, b=b@entry=0x55fddf6875b8, n=n@entry=37) at msort.c:53
#12 0x00007f09dac81a66 in msort_with_tmp (n=37, b=0x55fddf6875b8, p=0x7ffe1a79f520) at msort.c:45
#13 __GI___qsort_r (b=<optimized out>, n=<optimized out>, s=8, cmp=cmp@entry=0x55fddc1b9eb0 <cmpTitle_Bookmark_>, arg=arg@entry=0x0) at msort.c:297
#14 0x00007f09dac81cf8 in __GI_qsort (b=<optimized out>, n=<optimized out>, s=<optimized out>, cmp=cmp@entry=0x55fddc1b9eb0 <cmpTitle_Bookmark_>) at msort.c:308
#15 0x000055fddc2054f5 in sort_Array (d=d@entry=0x55fddf716060, cmp=cmp@entry=0x55fddc1b9eb0 <cmpTitle_Bookmark_>) at ../lib/the_Foundation/src/array.c:344
#16 0x000055fddc182eff in list_Bookmarks (d=0x55fddc6eb6a0, cmp=cmp@entry=0x55fddc1b9eb0 <cmpTitle_Bookmark_>, filter=filter@entry=0x0, context=context@entry=0x0) at ../src/bookmarks.c:273
#17 0x000055fddc1bbc9c in updateItems_SidebarWidget_ (d=d@entry=0x55fddf522df0) at ../src/ui/sidebarwidget.c:222
#18 0x000055fddc1bd58a in processEvent_SidebarWidget_ (d=0x55fddf522df0, ev=0x7ffe1a79fb20) at ../src/ui/sidebarwidget.c:820
#19 0x000055fddc1ff6c1 in dispatchEvent_Widget (d=0x55fddf522df0, ev=ev@entry=0x7ffe1a79fb20) at ../src/ui/widget.c:547
#20 0x000055fddc1ff69d in dispatchEvent_Widget (d=0x55fddf53e770, ev=ev@entry=0x7ffe1a79fb20) at ../src/ui/widget.c:535
#21 0x000055fddc1ff69d in dispatchEvent_Widget (d=0x55fddf53e5b0, ev=ev@entry=0x7ffe1a79fb20) at ../src/ui/widget.c:535
#22 0x000055fddc1ff69d in dispatchEvent_Widget (d=0x55fddf532970, ev=ev@entry=0x7ffe1a79fb20) at ../src/ui/widget.c:535
#23 0x000055fddc1ff69d in dispatchEvent_Widget (d=d@entry=0x55fddf52e540, ev=ev@entry=0x7ffe1a79fb20) at ../src/ui/widget.c:535
#24 0x000055fddc1fd711 in processEvent_Window (d=0x55fddc335d80, ev=ev@entry=0x7ffe1a79fbf0) at ../src/ui/window.c:956
#25 0x000055fddc180a33 in processEvents_App (eventMode=eventMode@entry=waitForNewEvents_AppEventMode) at ../src/app.c:625
#26 0x000055fddc181547 in run_App_ (d=0x55fddc242240 <app_>) at ../src/app.c:707
#27 run_App (argc=argc@entry=1, argv=argv@entry=0x7ffe1a79fe58) at ../src/app.c:770
#28 0x000055fddc17d6f0 in main (argc=1, argv=0x7ffe1a79fe58) at ../src/main.c:64
```

**Comment by skyjake** [comment]
This has probably been happening since v1.1.0 when the bookmark grouping was introduced.
