### ISSUE TITLE
Long touching tab crashes lagrange

### ISSUE THREAD

**Issue by paper42** [skyjake/lagrange#277]
When pressing a tab for longer time (1s), I get a crash. This only happens with touch input.

found on 1.4.1 built from source 
```
warning: Can't open file /memfd:pulseaudio (deleted) during file-backed mapping note processing
warning: Can't open file /memfd:xshmfence (deleted) during file-backed mapping note processing
warning: Corrupted shared library list: 0x7f79e3038ed0 != 0xc6c73138d4d50152
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `lagrange'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f79e227edc0 (LWP 20991))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f79e3517536 in __GI_abort () at abort.c:79
#2  0x00007f79e351741f in __assert_fail_base (fmt=0x7f79e367fea8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x56284d1ecf4d "activeRoot_", file=0x56284d1ecf3c "../src/ui/root.c", line=260, function=<optimized out>) at assert.c:92
#3  0x00007f79e3526792 in __GI___assert_fail (assertion=assertion@entry=0x56284d1ecf4d "activeRoot_", file=file@entry=0x56284d1ecf3c "../src/ui/root.c", line=line@entry=260, function=function@entry=0x56284d1ed998 <__PRETTY_FUNCTION__.11> "get_Root") at assert.c:101
#4  0x000056284d1566b5 in get_Root () at ../src/ui/root.c:260
#5  0x000056284d157c53 in get_Root () at ../src/ui/root.c:259
#6  0x000056284d1782b6 in dispatchNotification_Touch_ (code=4, d=0x56284e7be9c0) at ../src/ui/touch.c:230
#7  dispatchNotification_Touch_ (code=4, d=0x56284e7be9c0) at ../src/ui/touch.c:228
#8  update_TouchState_ (ptr=0x56284d228920 <state_>) at ../src/ui/touch.c:269
#9  0x000056284d1103f6 in runTickers_App_ (d=0x56284d21b5c0 <app_>) at ../src/app.c:1162
#10 run_App_ (d=<optimized out>) at ../src/app.c:1203
#11 run_App (argc=argc@entry=1, argv=argv@entry=0x7ffe148ab488) at ../src/app.c:1291
#12 0x000056284d109980 in main (argc=1, argv=0x7ffe148ab488) at ../src/main.c:74
```

**Comment by skyjake** [comment]
This may now be fixed in the dev branch. I've been fixing a bunch of related issues in the mobile build.

**Comment by skyjake** [comment]
I've closed this but haven't been able to test if v1.4.2 actually contains all the required fixes. The dev branch has more changes in touch event handling that haven't been merged to the release branch. v1.5 is due for release in a week, so if further issues remain, they will be fixed then.

**Comment by paper42** [comment]
I am still getting the same error in 1.4.2, the dev branch works great, thank you.

**Comment by skyjake** [comment]
Thanks for testing!
