### ISSUE TITLE
Crash on some keyboard shortcuts when the Preferences window is focused

### ISSUE THREAD

**Issue by the-blank-x** [skyjake/lagrange#583]
## Expected behavior
The keyboard shortcut to be ignored, or at least happen and not crash.

## Actual behavior
A null pointer dereference/crash

## Reproduction steps
- Open Lagrange
- Open the Preferences window (either with `Ctrl+,` or the menu item)
- Press `Ctrl+T`, `Ctrl+Shift+T`, or `Ctrl+Shift+I`

## Additional Information
Reproducible for version 1.15.3 and current `dev` (77bbc582ee721ec0e43c7eaa60f9967967f71b09) on Arch Linux and XWayland.
Backtrace for Ctrl+T (on commit 77bbc582ee721ec0e43c7eaa60f9967967f71b09):
```
#0  0x00005555555dce3c in newTab_App (duplicateOf=0x0, switchToNew=0x1) at /home/blankie/gits/lagrange/src/app.c:2916
#1  0x00005555555d704e in handleCommand_App (cmd=0x555556f93760 "tabs.new keydown:1") at /home/blankie/gits/lagrange/src/app.c:4205
#2  0x0000555555652aab in handleRootCommands_Widget (root=0x55555764b7c0, cmd=0x555556f93760 "tabs.new keydown:1") at /home/blankie/gits/lagrange/src/ui/root.c:609
#3  0x00005555556bdd90 in processEvent_Widget (d=0x55555764b7c0, ev=0x7fffffffe1e0) at /home/blankie/gits/lagrange/src/ui/widget.c:1562
#4  0x00005555556bc98a in dispatchEvent_Widget (d=0x55555764b7c0, ev=0x7fffffffe1e0) at /home/blankie/gits/lagrange/src/ui/widget.c:1307
#5  0x0000555555696348 in dispatchEvent_Window (d=0x555556bd99e0, ev=0x7fffffffe1e0) at /home/blankie/gits/lagrange/src/ui/window.c:1449
#6  0x0000555555695711 in processEvent_Window (d=0x555556bd99e0, ev=0x7fffffffe400) at /home/blankie/gits/lagrange/src/ui/window.c:1325
#7  0x00005555555d1ad4 in processEvents_App (eventMode=waitForNewEvents_AppEventMode) at /home/blankie/gits/lagrange/src/app.c:2047
#8  0x00005555555db264 in run_App_ (d=0x555555739178 <app_>) at /home/blankie/gits/lagrange/src/app.c:2246
#9  0x00005555555d9e7e in run_App (argc=0x1, argv=0x7fffffffe5d8) at /home/blankie/gits/lagrange/src/app.c:2406
#10 0x00005555555cf967 in main (argc=0x1, argv=0x7fffffffe5d8) at /home/blankie/gits/lagrange/src/main.c:90
```

**Comment by skyjake** [comment]
Thanks for reporting. I will fix these in the next patch.
